[tool.black]
line-length = 80
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 80
include_trailing_comma = true

[tool.pylint.'MESSAGES CONTROL']
max-line-length=80
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "no-name-in-module",
    "too-many-arguments",
    "duplicate-code",
    "invalid-name"
]
